Allow to edit topics from the file edit form
humhub/cfiles pull request #124
Opened 2021-08-06 06:06 UTC by yurabakhtin

Issue: https://github.com/humhub/cfiles/issues/103

2021-08-06 07:17 UTC, yurabakhtin commented
@luke- I cannot find why the test https://github.com/humhub/cfiles/runs/3259752013?check_suite_focus=true#step:25:70 is broken, because on my side it works:

<img width="2077" alt="cfiles_tests" src="https://user-images.githubusercontent.com/6995524/128471850-411ef7da-cb49-4280-bf00-a3ccfb3a4cf6.png">

2021-08-06 17:28 UTC, luke- approved these changes

2021-08-08 16:12 UTC, luke- approved these changes

2021-08-09 12:28 UTC, luke- requested changes

2021-08-09 12:28 UTC, luke- commented on models/File.php
> +        Topic::attach($this->content, $this->topics);
@yurabakhtin This line causes the test error on my system.

2021-08-10 12:14 UTC, luke- approved these changes

2021-08-10 12:14 UTC, merged