Use RichText for file description
humhub/cfiles pull request #125
Opened 2021-08-06 06:28 UTC by yurabakhtin

Issue: https://github.com/humhub/cfiles/issues/48

2021-08-06 17:11 UTC, luke- requested changes
@yurabakhtin When saving richtext, the uploaded file must still be linked somewhere or?

2021-08-11 11:16 UTC, yurabakhtin commented
@luke- I am not sure I got your question clearly, but the description is just saved into the column `cfiles_file:description`, so no reason how the file will be linked or will not.

2021-08-11 11:36 UTC, luke- commented
@yurabakhtin Steps to reproduce:

1. Upload a file
2. Edit description and insert an image using the Richtext Editior "Upload file" option
3. Check the `files` table

![image](https://user-images.githubusercontent.com/4736168/129022121-f202d9df-62a5-4905-adfd-3397ffde2ba4.png)

4. Image (not linked) will be deleted after 48hours.

2021-08-11 12:53 UTC, yurabakhtin commented
@luke- Ok, I have understood the problem and fixed in commit https://github.com/humhub/cfiles/pull/125/commits/e342981cba62af67abfae13e1fb7adc5e3c7042f.

2021-08-11 15:33 UTC, luke- approved these changes

2021-08-11 15:34 UTC, merged